apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: msa-generator
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30004
