apiVersion: v1
kind: Service
metadata:
  name: planner-service
  namespace: msa-generator
spec:
  type: NodePort
  selector:
    app: planner
  ports:
  - port: 8002
    targetPort: 8002
    nodePort: 30003
