apiVersion: v1
kind: Service
metadata:
  name: summarizer-service
  namespace: msa-generator
spec:
  type: NodePort
  selector:
    app: summarizer
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 30002
