apiVersion: v1
kind: Service
metadata:
  name: upload-service
  namespace: msa-generator
spec:
  type: NodePort
  selector:
    app: upload
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001
